name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: oracle
      - run: ./gradlew test
        working-directory: ./server
